### ISSUE TITLE
./bin/seed errors out when trying to get bucket

### ISSUE THREAD

**Issue by rberger** [hw-labs/infrastructure-repository#2]
When I try to run ./bin/seed for the first time it errors out:

```
[InfraRepo]: Write stable asset to bucket... writing
/Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-aws-0.3.2/lib/miasma/contrib/aws/storage.rb:164:in `join': no implicit conversion of nil into String (TypeError)
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-aws-0.3.2/lib/miasma/contrib/aws/storage.rb:164:in `bucket_endpoint'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-aws-0.3.2/lib/miasma/contrib/aws/storage.rb:223:in `block in file_all'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-aws-0.3.2/lib/miasma/contrib/aws/storage.rb:33:in `all_result_pages'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-aws-0.3.2/lib/miasma/contrib/aws/storage.rb:219:in `file_all'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-0.3.2/lib/miasma/models/storage/files.rb:50:in `perform_population'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-0.3.2/lib/miasma/types/collection.rb:22:in `block in all'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/bogo-0.2.4/lib/bogo/memoization.rb:64:in `memoize'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-0.3.2/lib/miasma/types/collection.rb:21:in `all'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-0.3.2/lib/miasma/types/collection.rb:108:in `perform_get'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-0.3.2/lib/miasma/types/collection.rb:40:in `block in get'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/bogo-0.2.4/lib/bogo/memoization.rb:64:in `memoize'
    from /Users/rberger/.rvm/gems/ruby-2.3.0/gems/miasma-0.3.2/lib/miasma/types/collection.rb:39:in `get'
    from ./bin/seed:201:in `<main>'
```

**Comment by rberger** [comment]
Looks like something in the infrastructure-repository bin/seed doen't like miasma-aws > 0.2.x.

I locked the Gemfile entry for miasma-aws to 0.2.4 (the last release before 0.3) and it works fine.
